#!/usr/bin/env python

import pyglet

window = pyglet.window.Window()

batch = pyglet.graphics.Batch()

paddle_image = pyglet.image.load("pong/images/paddle.png")
left_paddle = pyglet.sprite.Sprite(
    paddle_image,
    x=50,
    y=50
)
left_paddle.batch = batch
left_paddle.scale = 20
right_paddle = pyglet.sprite.Sprite(
    paddle_image,
    x=window.width-50,
    y=50,
)
right_paddle.scale = 20
right_paddle.batch = batch

@window.event
def on_draw():
    window.clear()
    batch.draw()

pyglet.app.run()
